[2024-11-03T01:40:45.736+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-03T01:40:45.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: songs_preprocessing.clean_data_task manual__2024-11-03T01:40:33.955830+00:00 [queued]>
[2024-11-03T01:40:45.891+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: songs_preprocessing.clean_data_task manual__2024-11-03T01:40:33.955830+00:00 [queued]>
[2024-11-03T01:40:45.891+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-03T01:40:45.920+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_data_task> on 2024-11-03 01:40:33.955830+00:00
[2024-11-03T01:40:45.935+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=746) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T01:40:45.938+0000] {standard_task_runner.py:63} INFO - Started process 763 to run task
[2024-11-03T01:40:45.938+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'songs_preprocessing', 'clean_data_task', 'manual__2024-11-03T01:40:33.955830+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpyngvwaiy']
[2024-11-03T01:40:45.942+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask clean_data_task
[2024-11-03T01:40:46.037+0000] {task_command.py:426} INFO - Running <TaskInstance: songs_preprocessing.clean_data_task manual__2024-11-03T01:40:33.955830+00:00 [running]> on host 4a174f3124db
[2024-11-03T01:40:46.195+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='songs_preprocessing' AIRFLOW_CTX_TASK_ID='clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T01:40:33.955830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T01:40:33.955830+00:00'
[2024-11-03T01:40:46.196+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-03T01:40:46.216+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-03T01:40:46.217+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/song_recommendation.py", line 47, in data_cleaning
    df[df['song_name'].isnull()]
       ~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-11-03T01:40:46.229+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=songs_preprocessing, task_id=clean_data_task, run_id=manual__2024-11-03T01:40:33.955830+00:00, execution_date=20241103T014033, start_date=20241103T014045, end_date=20241103T014046
[2024-11-03T01:40:46.245+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task clean_data_task ('NoneType' object is not subscriptable; 763)
[2024-11-03T01:40:46.281+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-03T01:40:46.310+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T01:40:46.325+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
