[2024-11-03T01:42:41.520+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-03T01:42:41.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: songs_preprocessing.clean_data_task manual__2024-11-03T01:42:28.487994+00:00 [queued]>
[2024-11-03T01:42:41.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: songs_preprocessing.clean_data_task manual__2024-11-03T01:42:28.487994+00:00 [queued]>
[2024-11-03T01:42:41.679+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-03T01:42:41.698+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_data_task> on 2024-11-03 01:42:28.487994+00:00
[2024-11-03T01:42:41.716+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=811) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T01:42:41.720+0000] {standard_task_runner.py:63} INFO - Started process 828 to run task
[2024-11-03T01:42:41.718+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'songs_preprocessing', 'clean_data_task', 'manual__2024-11-03T01:42:28.487994+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp2zipgyau']
[2024-11-03T01:42:41.721+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask clean_data_task
[2024-11-03T01:42:41.770+0000] {task_command.py:426} INFO - Running <TaskInstance: songs_preprocessing.clean_data_task manual__2024-11-03T01:42:28.487994+00:00 [running]> on host 4a174f3124db
[2024-11-03T01:42:41.894+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='songs_preprocessing' AIRFLOW_CTX_TASK_ID='clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T01:42:28.487994+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T01:42:28.487994+00:00'
[2024-11-03T01:42:41.895+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-03T01:42:41.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-03T01:42:41.915+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/song_recommendation.py", line 48, in data_cleaning
    df = df.dropna(subset=['song_name', 'uri'])
         ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-11-03T01:42:41.931+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=songs_preprocessing, task_id=clean_data_task, run_id=manual__2024-11-03T01:42:28.487994+00:00, execution_date=20241103T014228, start_date=20241103T014241, end_date=20241103T014241
[2024-11-03T01:42:41.945+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task clean_data_task ('NoneType' object has no attribute 'dropna'; 828)
[2024-11-03T01:42:41.983+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-03T01:42:42.003+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T01:42:42.007+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
